[package]
name = "revtypst"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Tobias M. R. Wolf"]
license = "GPL-3.0-only"
description = "A template for writing journal articles (inspired by revtex / APS journal guidelines)."

[template]
path = "template"
entrypoint = "main.typ"
